import { uiEn, type UiMessages } from "@/i18n/ui/en";

/** German UI chrome — clear, natural German. */
export const uiDe: UiMessages = {
  ...uiEn,
  language: "Sprache", menu: "Menü", close: "Schließen", open: "Öffnen", skipToContent: "Zum Inhalt springen",
  nav: { home: "Startseite", technology: "Technologie", systems: "Systeme", applications: "Anwendungen", trust: "Vertrauen", research: "Forschung", purpose: "Zweck", foundation: "Grundlagen" },
  navEntries: { ...uiEn.navEntries, "technology-overview": "Technologie", "technology-human-data": "Menschliche Daten", "technology-human-data-model": "Modell menschlicher Daten", "technology-data-infrastructure": "Dateninfrastruktur", "technology-interoperability": "Interoperabilität", "technology-privacy": "Datenschutz", "technology-security": "Sicherheit", "technology-artificial-intelligence": "Künstliche Intelligenz", "technology-automation": "Automatisierung", "technology-robotics": "Robotik", "systems-overview": "Systeme", "systems-knowledge-engine": "Wissenssystem", "systems-ai-decision-support": "KI-gestützte Entscheidungsunterstützung", "systems-safety-layer": "Sicherheitsschicht", "systems-communication-layer": "Kommunikationsschicht", "systems-clinical-interfaces": "Klinische Schnittstellen", "systems-robotics-layer": "Robotikschicht", "systems-drone-systems": "Drohnen-Systeme", "applications-overview": "Anwendungen", "applications-healthcare": "Gesundheitswesen", "applications-home": "Zuhause", "applications-hospitals": "Krankenhäuser", "applications-emergency": "Notfälle", "applications-industrial": "Industrie", "applications-government": "Öffentlicher Sektor", "applications-agriculture": "Landwirtschaft", "applications-research-applications": "Forschungsanwendungen", "trust-overview": "Vertrauen", "trust-privacy": "Datenschutz", "trust-security": "Sicherheit", "trust-safety": "Schutz", "trust-human-oversight": "Menschliche Aufsicht", "trust-transparency": "Transparenz", "trust-ethics": "Ethik und verantwortungsvolle Nutzung", "trust-limitations": "Grenzen", "research-overview": "Forschung", "footer-purpose": "Zweck", "footer-foundation": "Grundlagen", "footer-research": "Forschung", "footer-resources-purpose": "Zweck", "footer-resources-foundation": "Grundlagen", "footer-resources-research": "Forschung", "footer-resources-home": "Startseite" },
  footer: { ...uiEn.footer, technology: "Technologie", systems: "Systeme", applications: "Anwendungen", trust: "Vertrauen", research: "Forschung", about: "Über SAVEN Core", resources: "Ressourcen", company: "Unternehmen", legal: "Rechtliches", contact: "Kontakt", plannedNote: "Kommt später.", comingSoon: "Demnächst", copyright: "© 2026 SAVEN Core. Alle Rechte vorbehalten.", copyrightShort: "© SAVEN Core", privacy: "Datenschutz", terms: "Bedingungen", cookies: "Cookies", theme: "Design", themeLight: "Hell", themeDark: "Dunkel", version: "Version", tagline: "Intelligente Systeme zur Unterstützung menschlichen Lebens." },
  home: { developmentStatus: "Wo wir stehen", architectureOverview: "Die Idee auf einen Blick", architectureOverviewText: "Von Menschen und Informationen zu Systemen, die im Alltag unterstützen — innerhalb klarer Grenzen.", knowledgeExplorer: "Entdecken", majorDomains: "Hauptthemen", publishedPages: "Seiten hier", relationships: "Wie es zusammenhängt", domainMap: "Entdecken", architectureDependencies: "Wie die Themen zusammenpassen", currentStatus: "Fortschritt", platformProgress: "Was bereit ist", featuredConcepts: "Entdecken", startWithCore: "Einige Ideen für den Einstieg", continueExploring: "Weiter", chooseEntrance: "Wählen Sie einen Ausgangspunkt", knowledgeId: "Dokument-ID", complete: "Abgeschlossen", inProgress: "In Bearbeitung", planned: "Geplant", understand: "Verstehen", explore: "Erkunden", discover: "Entdecken", continue: "Weiter" },
  ko: { ...uiEn.ko, document: "Dokument", passport: "Dokumentinformationen", knowledgeId: "Dokument-ID", domain: "Themenbereich", type: "Dokumenttyp", status: "Status", version: "Version", evidence: "Evidenz", maturity: "Status", readingTime: "Lesezeit", lastReview: "Letzte Überprüfung", owner: "Verantwortlich", engineeringObject: "Seiteninformationen", currentPosition: "Sie sind hier", nextReading: "Nächste Leseempfehlung", notYetAssigned: "Noch nicht zugewiesen.", dependencies: "Verwandte Konzepte", dependencyGraph: "Verwandte Konzepte", incoming: "Verwendet von", outgoing: "Basiert auf", nonePublished: "Noch keine", knowledgeGraph: "Verbindungen", parents: "Übergeordnete Themen", children: "Enthaltene Themen", consumers: "Verwendet von", providers: "Basiert auf", lifecycle: "Dokumentverlauf", created: "Erstellt", reviewed: "Überprüft", published: "Veröffentlicht", updated: "Aktualisiert", nextReview: "Nächste Überprüfung", deprecated: "Veraltet", futureRevision: "Künftige Überarbeitung", versionHistory: "Versionen", previousVersion: "Vorherige Version", summaryOfChanges: "Was sich geändert hat", date: "Datum", readingPaths: "Leseempfehlungen", level2Kicker: "Als Nächstes", level2Title: "Verwandte Lektüre und Konzepte", level3Kicker: "Details", level3Title: "Dokumentinformationen für Fachleute" },
  scope: { definition: "Definition", "current-scope": "Was dies abdeckt", "future-scope": "Was als Nächstes kommt", "human-oversight": "Menschliche Aufsicht", "safety-boundary": "Sicherheitsgrenze", "engineering-note": "Hinweise", limitation: "Grenze" },
  callout: { information: "Information", definition: "Definition", "engineering-note": "Hinweise", important: "Wichtig", "current-scope": "Was dies abdeckt", "future-scope": "Was als Nächstes kommt", relationship: "Verbindung" },
  common: { openArrow: "Öffnen", relatedDomains: "Verwandte Themen", referenceLinks: "Weiterlesen", keyPrinciples: "Kernprinzipien", executiveSummary: "Zusammenfassung", whyItMatters: "Warum es wichtig ist", purpose: "Zweck", futureExpansion: "Was als Nächstes kommt" },
};
