import { uiEn, type UiMessages } from "@/i18n/ui/en";

/** Spanish UI chrome — clear, neutral international Spanish. */
export const uiEs: UiMessages = {
  ...uiEn,
  language: "Idioma", menu: "Menú", close: "Cerrar", open: "Abrir", skipToContent: "Ir al contenido",
  nav: { home: "Inicio", technology: "Tecnología", systems: "Sistemas", applications: "Aplicaciones", trust: "Confianza", research: "Investigación", purpose: "Propósito", foundation: "Fundamentos" },
  navEntries: { ...uiEn.navEntries, "technology-overview": "Tecnología", "technology-human-data": "Datos humanos", "technology-human-data-model": "Modelo de datos humanos", "technology-data-infrastructure": "Infraestructura de datos", "technology-interoperability": "Interoperabilidad", "technology-privacy": "Privacidad", "technology-security": "Seguridad", "technology-artificial-intelligence": "Inteligencia artificial", "technology-automation": "Automatización", "technology-robotics": "Robótica", "systems-overview": "Sistemas", "systems-knowledge-engine": "Motor de conocimiento", "systems-ai-decision-support": "Apoyo a la decisión con IA", "systems-safety-layer": "Capa de seguridad", "systems-communication-layer": "Capa de comunicación", "systems-clinical-interfaces": "Interfaces clínicas", "systems-robotics-layer": "Capa de robótica", "systems-drone-systems": "Sistemas de drones", "applications-overview": "Aplicaciones", "applications-healthcare": "Atención sanitaria", "applications-home": "Hogar", "applications-hospitals": "Hospitales", "applications-emergency": "Emergencias", "applications-industrial": "Industria", "applications-government": "Gobierno", "applications-agriculture": "Agricultura", "applications-research-applications": "Aplicaciones de investigación", "trust-overview": "Confianza", "trust-privacy": "Privacidad", "trust-security": "Seguridad", "trust-safety": "Protección", "trust-human-oversight": "Supervisión humana", "trust-transparency": "Transparencia", "trust-ethics": "Ética y uso responsable", "trust-limitations": "Limitaciones", "research-overview": "Investigación", "footer-purpose": "Propósito", "footer-foundation": "Fundamentos", "footer-research": "Investigación", "footer-resources-purpose": "Propósito", "footer-resources-foundation": "Fundamentos", "footer-resources-research": "Investigación", "footer-resources-home": "Inicio" },
  footer: { technology: "Tecnología", systems: "Sistemas", applications: "Aplicaciones", trust: "Confianza", research: "Investigación", about: "Acerca de SAVEN Core", resources: "Recursos", company: "Empresa", legal: "Legal", contact: "Contacto", plannedNote: "Próximamente.", copyright: "© 2026 SAVEN Core. Todos los derechos reservados." },
  home: { developmentStatus: "Dónde estamos", architectureOverview: "La idea de un vistazo", architectureOverviewText: "De las personas y la información a sistemas que ayudan en la vida cotidiana, dentro de límites claros.", knowledgeExplorer: "Explorar", majorDomains: "Temas principales", publishedPages: "Páginas aquí", relationships: "Cómo se conecta", domainMap: "Descubrir", architectureDependencies: "Cómo encajan los temas", currentStatus: "Progreso", platformProgress: "Qué está listo", featuredConcepts: "Descubrir", startWithCore: "Algunas ideas para empezar", continueExploring: "Continuar", chooseEntrance: "Elige por dónde empezar", knowledgeId: "ID del documento", complete: "Completo", inProgress: "En curso", planned: "Planificado", understand: "Entender", explore: "Explorar", discover: "Descubrir", continue: "Continuar" },
  ko: { ...uiEn.ko, document: "Documento", passport: "Información del documento", knowledgeId: "ID del documento", domain: "Área temática", type: "Tipo de documento", status: "Estado", version: "Versión", evidence: "Evidencia", maturity: "Estado", readingTime: "Tiempo de lectura", lastReview: "Última revisión", owner: "Responsable", engineeringObject: "Información de la página", currentPosition: "Estás aquí", nextReading: "Siguiente lectura sugerida", notYetAssigned: "Aún no asignado.", dependencies: "Conceptos relacionados", dependencyGraph: "Conceptos relacionados", incoming: "Utilizado por", outgoing: "Depende de", nonePublished: "Aún no hay", knowledgeGraph: "Conexiones", parents: "Temas más amplios", children: "Temas incluidos", consumers: "Utilizado por", providers: "Basado en", lifecycle: "Historial del documento", created: "Creado", reviewed: "Revisado", published: "Publicado", updated: "Actualizado", nextReview: "Próxima revisión", deprecated: "Obsoleto", futureRevision: "Revisión futura", versionHistory: "Versiones", previousVersion: "Versión anterior", summaryOfChanges: "Qué cambió", date: "Fecha", readingPaths: "Lectura sugerida", level2Kicker: "Siguiente", level2Title: "Lecturas y conceptos relacionados", level3Kicker: "Detalles", level3Title: "Información del documento para profesionales" },
  scope: { definition: "Definición", "current-scope": "Qué cubre esto", "future-scope": "Qué sigue", "human-oversight": "Supervisión humana", "safety-boundary": "Límite de seguridad", "engineering-note": "Notas", limitation: "Límite" },
  callout: { information: "Información", definition: "Definición", "engineering-note": "Notas", important: "Importante", "current-scope": "Qué cubre esto", "future-scope": "Qué sigue", relationship: "Conexión" },
  common: { openArrow: "Abrir", relatedDomains: "Temas relacionados", referenceLinks: "Más para leer", keyPrinciples: "Principios clave", executiveSummary: "Resumen", whyItMatters: "Por qué importa", purpose: "Propósito", futureExpansion: "Qué sigue" },
};
