import { uiEn, type UiMessages } from "@/i18n/ui/en";

/** French UI chrome — clear, natural international French. */
export const uiFr: UiMessages = {
  ...uiEn,
  language: "Langue", menu: "Menu", close: "Fermer", open: "Ouvrir", skipToContent: "Aller au contenu",
  nav: { home: "Accueil", technology: "Technologie", systems: "Systèmes", applications: "Applications", trust: "Confiance", research: "Recherche", purpose: "Raison d’être", foundation: "Fondations" },
  navEntries: { ...uiEn.navEntries, "technology-overview": "Technologie", "technology-human-data": "Données humaines", "technology-human-data-model": "Modèle de données humaines", "technology-data-infrastructure": "Infrastructure de données", "technology-interoperability": "Interopérabilité", "technology-privacy": "Confidentialité", "technology-security": "Sécurité", "technology-artificial-intelligence": "Intelligence artificielle", "technology-automation": "Automatisation", "technology-robotics": "Robotique", "systems-overview": "Systèmes", "systems-knowledge-engine": "Moteur de connaissances", "systems-ai-decision-support": "Aide à la décision par IA", "systems-safety-layer": "Couche de sécurité", "systems-communication-layer": "Couche de communication", "systems-clinical-interfaces": "Interfaces cliniques", "systems-robotics-layer": "Couche robotique", "systems-drone-systems": "Systèmes de drones", "applications-overview": "Applications", "applications-healthcare": "Santé", "applications-home": "Domicile", "applications-hospitals": "Hôpitaux", "applications-emergency": "Urgences", "applications-industrial": "Industrie", "applications-government": "Secteur public", "applications-agriculture": "Agriculture", "applications-research-applications": "Applications de recherche", "trust-overview": "Confiance", "trust-privacy": "Confidentialité", "trust-security": "Sécurité", "trust-safety": "Protection", "trust-human-oversight": "Supervision humaine", "trust-transparency": "Transparence", "trust-ethics": "Éthique et usage responsable", "trust-limitations": "Limites", "research-overview": "Recherche", "footer-purpose": "Raison d’être", "footer-foundation": "Fondations", "footer-research": "Recherche", "footer-resources-purpose": "Raison d’être", "footer-resources-foundation": "Fondations", "footer-resources-research": "Recherche", "footer-resources-home": "Accueil" },
  footer: { ...uiEn.footer, technology: "Technologie", systems: "Systèmes", applications: "Applications", trust: "Confiance", research: "Recherche", about: "À propos de SAVEN Core", resources: "Ressources", company: "Entreprise", legal: "Mentions légales", contact: "Contact", plannedNote: "À venir.", comingSoon: "Bientôt", copyright: "© 2026 SAVEN Core. Tous droits réservés.", copyrightShort: "© SAVEN Core", privacy: "Confidentialité", terms: "Conditions", cookies: "Cookies", theme: "Thème", themeLight: "Clair", themeDark: "Sombre", version: "Version", tagline: "Données humaines.\nSystèmes connectés.\nTechnologie responsable." },
  home: { developmentStatus: "Où nous en sommes", architectureOverview: "L’idée en un regard", architectureOverviewText: "Des personnes et de l’information aux systèmes qui aident dans la vie quotidienne — dans des limites claires.", knowledgeExplorer: "Explorer", majorDomains: "Sujets principaux", publishedPages: "Pages ici", relationships: "Comment cela se relie", domainMap: "Découvrir", architectureDependencies: "Comment les sujets s’articulent", currentStatus: "Avancement", platformProgress: "Ce qui est prêt", featuredConcepts: "Découvrir", startWithCore: "Quelques idées pour commencer", continueExploring: "Continuer", chooseEntrance: "Choisissez un point de départ", knowledgeId: "ID du document", complete: "Terminé", inProgress: "En cours", planned: "Prévu", understand: "Comprendre", explore: "Explorer", discover: "Découvrir", continue: "Continuer" },
  ko: { ...uiEn.ko, document: "Document", passport: "Informations sur le document", knowledgeId: "ID du document", domain: "Domaine thématique", type: "Type de document", status: "Statut", version: "Version", evidence: "Éléments probants", maturity: "Statut", readingTime: "Temps de lecture", lastReview: "Dernière révision", owner: "Responsable", engineeringObject: "Informations sur la page", currentPosition: "Vous êtes ici", nextReading: "Lecture suggérée", notYetAssigned: "Pas encore attribué.", dependencies: "Concepts associés", dependencyGraph: "Concepts associés", incoming: "Utilisé par", outgoing: "Dépend de", nonePublished: "Aucun pour le moment", knowledgeGraph: "Connexions", parents: "Sujets plus généraux", children: "Sujets inclus", consumers: "Utilisé par", providers: "S’appuie sur", lifecycle: "Historique du document", created: "Créé", reviewed: "Révisé", published: "Publié", updated: "Mis à jour", nextReview: "Prochaine révision", deprecated: "Obsolète", futureRevision: "Révision future", versionHistory: "Versions", previousVersion: "Version précédente", summaryOfChanges: "Ce qui a changé", date: "Date", readingPaths: "Lectures suggérées", level2Kicker: "Ensuite", level2Title: "Lectures et concepts associés", level3Kicker: "Détails", level3Title: "Informations du document pour les professionnels" },
  scope: { definition: "Définition", "current-scope": "Ce que cela couvre", "future-scope": "La suite", "human-oversight": "Supervision humaine", "safety-boundary": "Limite de sécurité", "engineering-note": "Notes", limitation: "Limite" },
  callout: { information: "Information", definition: "Définition", "engineering-note": "Notes", important: "Important", "current-scope": "Ce que cela couvre", "future-scope": "La suite", relationship: "Lien" },
  common: { openArrow: "Ouvrir", relatedDomains: "Sujets associés", referenceLinks: "Pour aller plus loin", keyPrinciples: "Principes clés", executiveSummary: "Résumé", whyItMatters: "Pourquoi c’est important", purpose: "Raison d’être", futureExpansion: "La suite" },
};
