import { uiEn, type UiMessages } from "@/i18n/ui/en";

/** Simplified Chinese UI chrome — clear, natural Mandarin Chinese. */
export const uiZhCn: UiMessages = {
  ...uiEn,
  language: "语言", menu: "菜单", close: "关闭", open: "打开", skipToContent: "跳至内容",
  nav: { home: "首页", technology: "技术", systems: "系统", applications: "应用领域", trust: "信任", research: "研究", purpose: "宗旨", foundation: "基础" },
  navEntries: { ...uiEn.navEntries, "technology-overview": "技术", "technology-human-data": "人的数据", "technology-human-data-model": "人的数据模型", "technology-data-infrastructure": "数据基础设施", "technology-interoperability": "互操作性", "technology-privacy": "隐私", "technology-security": "安全", "technology-artificial-intelligence": "人工智能", "technology-automation": "自动化", "technology-robotics": "机器人技术", "systems-overview": "系统", "systems-knowledge-engine": "知识引擎", "systems-ai-decision-support": "AI 决策支持", "systems-safety-layer": "安全层", "systems-communication-layer": "通信层", "systems-clinical-interfaces": "临床接口", "systems-robotics-layer": "机器人层", "systems-drone-systems": "无人机系统", "applications-overview": "应用领域", "applications-healthcare": "医疗健康", "applications-home": "家庭", "applications-hospitals": "医院", "applications-emergency": "紧急情况", "applications-industrial": "工业", "applications-government": "政府", "applications-agriculture": "农业", "applications-research-applications": "研究应用", "trust-overview": "信任", "trust-privacy": "隐私", "trust-security": "安全", "trust-safety": "保障", "trust-human-oversight": "人工监督", "trust-transparency": "透明度", "trust-ethics": "伦理与负责任使用", "trust-limitations": "局限", "research-overview": "研究", "footer-purpose": "宗旨", "footer-foundation": "基础", "footer-research": "研究", "footer-resources-purpose": "宗旨", "footer-resources-foundation": "基础", "footer-resources-research": "研究", "footer-resources-home": "首页" },
  footer: { ...uiEn.footer, technology: "技术", systems: "系统", applications: "应用领域", trust: "信任", research: "研究", about: "关于 SAVEN Core", resources: "资源", company: "公司", legal: "法律信息", contact: "联系我们", plannedNote: "即将推出。", comingSoon: "即将推出", copyright: "© 2026 SAVEN Core. 保留所有权利。", copyrightShort: "© SAVEN Core", privacy: "隐私", terms: "条款", cookies: "Cookie", theme: "主题", themeLight: "浅色", themeDark: "深色", version: "版本", tagline: "人类数据。\n互联系统。\n负责任的技术。" },
  home: { developmentStatus: "我们目前所处的位置", architectureOverview: "一览核心理念", architectureOverviewText: "从人和信息到支持日常生活的系统——始终遵循明确的边界。", knowledgeExplorer: "探索", majorDomains: "主要主题", publishedPages: "这里的页面", relationships: "如何关联", domainMap: "发现", architectureDependencies: "主题如何衔接", currentStatus: "进展", platformProgress: "已准备好的内容", featuredConcepts: "发现", startWithCore: "从几个核心理念开始", continueExploring: "继续", chooseEntrance: "选择起点", knowledgeId: "文档 ID", complete: "完成", inProgress: "进行中", planned: "计划中", understand: "了解", explore: "探索", discover: "发现", continue: "继续" },
  ko: { ...uiEn.ko, document: "文档", passport: "文档信息", knowledgeId: "文档 ID", domain: "主题领域", type: "文档类型", status: "状态", version: "版本", evidence: "依据", maturity: "状态", readingTime: "阅读时间", lastReview: "最近审核", owner: "负责人", engineeringObject: "页面信息", currentPosition: "当前位置", nextReading: "建议接着阅读", notYetAssigned: "尚未指定。", dependencies: "相关概念", dependencyGraph: "相关概念", incoming: "被以下内容使用", outgoing: "依赖于", nonePublished: "暂无", knowledgeGraph: "关联", parents: "更广泛的主题", children: "包含的主题", consumers: "被以下内容使用", providers: "构建于", lifecycle: "文档历史", created: "已创建", reviewed: "已审核", published: "已发布", updated: "已更新", nextReview: "下次审核", deprecated: "已弃用", futureRevision: "未来修订", versionHistory: "版本", previousVersion: "上一版本", summaryOfChanges: "变更内容", date: "日期", readingPaths: "建议阅读", level2Kicker: "下一步", level2Title: "相关阅读与概念", level3Kicker: "详情", level3Title: "面向专业人士的文档信息" },
  scope: { definition: "定义", "current-scope": "涵盖内容", "future-scope": "下一步内容", "human-oversight": "人工监督", "safety-boundary": "安全边界", "engineering-note": "说明", limitation: "限制" },
  callout: { information: "信息", definition: "定义", "engineering-note": "说明", important: "重要", "current-scope": "涵盖内容", "future-scope": "下一步内容", relationship: "关联" },
  common: { openArrow: "打开", relatedDomains: "相关主题", referenceLinks: "延伸阅读", keyPrinciples: "关键原则", executiveSummary: "摘要", whyItMatters: "重要原因", purpose: "宗旨", futureExpansion: "下一步内容" },
};
