/**
 * Canonical knowledge entity registry — Phase 3.0.
 * Only Phase 2.1-approved entities. Relationship IDs are source of truth.
 */

import type { KnowledgeEntity } from "@/content/knowledge/entity-types";

function defineEntity(
  entity: KnowledgeEntity,
): KnowledgeEntity {
  return entity;
}

/**
 * Ordered foundation hierarchy root → leaf.
 * Validated in entity-registry.ts.
 */
export const FOUNDATION_HIERARCHY_IDS = [
  "biomath-life",
  "biomath-core",
  "saven",
  "saven-core",
] as const;

export type FoundationHierarchyId = (typeof FOUNDATION_HIERARCHY_IDS)[number];

export const knowledgeEntities: readonly KnowledgeEntity[] = [
  // —— Foundation ——
  defineEntity({
    id: "biomath-life",
    slug: "biomath-life",
    title: "BioMath Life",
    entityType: "foundation",
    domain: "foundation",
    summary:
      "Human-centered foundation for understanding the individual across biological, medical, behavioral, environmental and life context. Establishes why human understanding precedes product framing.",
    status: "foundational",
    parentId: null,
    childIds: ["biomath-core"],
    relatedEntityIds: ["human-data-model", "trust-architecture"],
    dependencyIds: [],
    usedByIds: ["biomath-core"],
    relatedTechnologyIds: ["human-data", "privacy"],
    relatedSystemIds: ["human-data-model", "safety-layer"],
    relatedResearchIds: ["research-areas", "future-research"],
    relatedApplicationIds: ["healthcare", "home"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Foundation", href: "/foundation/" },
      { label: "Purpose", href: "/purpose/" },
    ],
    futureTopics: [
      "Layer detail pages",
      "Guiding definitions index",
    ],
  }),
  defineEntity({
    id: "biomath-core",
    slug: "biomath-core",
    title: "BioMath Core",
    entityType: "foundation",
    domain: "foundation",
    summary:
      "Intelligence layer that organizes human data so context can be interpreted with permissions, privacy and accountable use. Turns human-centered understanding into structured models and decision assistance.",
    status: "foundational",
    parentId: "biomath-life",
    childIds: ["saven"],
    relatedEntityIds: ["human-data-model", "knowledge-engine"],
    dependencyIds: ["biomath-life"],
    usedByIds: ["saven"],
    relatedTechnologyIds: ["human-data", "artificial-intelligence", "privacy"],
    relatedSystemIds: ["human-data-model", "ai-decision-support", "knowledge-engine"],
    relatedResearchIds: ["research-areas", "engineering-notes"],
    relatedApplicationIds: ["healthcare", "hospitals", "home"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Foundation", href: "/foundation/" },
      { label: "Technology", href: "/technology/" },
    ],
    futureTopics: [
      "Human Data Model detail",
      "Permission model notes",
    ],
  }),
  defineEntity({
    id: "saven",
    slug: "saven",
    title: "SAVEN",
    entityType: "foundation",
    domain: "foundation",
    summary:
      "Execution layer connecting human understanding and intelligence with actions, workflows, devices and operational responses. Prepares the integration surface that SAVEN Core engineers as systems.",
    status: "foundational",
    parentId: "biomath-core",
    childIds: ["saven-core"],
    relatedEntityIds: ["robotics-layer", "ai-decision-support"],
    dependencyIds: ["biomath-core"],
    usedByIds: ["saven-core"],
    relatedTechnologyIds: ["robotics", "automation", "artificial-intelligence"],
    relatedSystemIds: [
      "robotics-layer",
      "ai-decision-support",
      "communication-layer",
    ],
    relatedResearchIds: ["research-areas", "laboratories"],
    relatedApplicationIds: ["home", "hospitals", "emergency"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Foundation", href: "/foundation/" },
      { label: "Systems", href: "/systems/" },
    ],
    futureTopics: [
      "Execution interface contracts",
      "Operational pattern notes",
    ],
  }),
  defineEntity({
    id: "saven-core",
    slug: "saven-core",
    title: "SAVEN Core",
    entityType: "foundation",
    domain: "foundation",
    summary:
      "Physical systems layer that integrates the human intelligence foundation with physical and digital systems under one engineering organization. Unifies prior layers into systems, technology disciplines and application contexts.",
    status: "active-development",
    parentId: "saven",
    childIds: [],
    relatedEntityIds: ["company", "trust-architecture"],
    dependencyIds: ["saven"],
    usedByIds: [],
    relatedTechnologyIds: [
      "artificial-intelligence",
      "robotics",
      "privacy",
      "security",
    ],
    relatedSystemIds: [
      "human-data-model",
      "robotics-layer",
      "safety-layer",
      "knowledge-engine",
    ],
    relatedResearchIds: ["research-areas", "laboratories", "engineering-notes"],
    relatedApplicationIds: [
      "healthcare",
      "home",
      "hospitals",
      "research",
    ],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Foundation", href: "/foundation/" },
      { label: "Applications", href: "/applications/" },
    ],
    futureTopics: [
      "System status registers",
      "Engineering method indexes",
    ],
  }),

  // —— Technology ——
  defineEntity({
    id: "artificial-intelligence",
    slug: "artificial-intelligence",
    title: "Artificial Intelligence",
    entityType: "technology",
    domain: "technology",
    summary:
      "Models and rules intended to assist judgment under permissions, uncertainty handling and human oversight. Supports context interpretation and controlled assistance within defined limits.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["ai-decision-support", "knowledge-engine"],
    dependencyIds: [],
    usedByIds: ["ai-decision-support", "knowledge-engine"],
    relatedTechnologyIds: ["automation", "human-data"],
    relatedSystemIds: [
      "ai-decision-support",
      "knowledge-engine",
      "safety-layer",
    ],
    relatedResearchIds: ["research-areas", "white-papers"],
    relatedApplicationIds: ["healthcare", "emergency", "hospitals"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Technology", href: "/technology/" }],
    futureTopics: [
      "Constrained inference patterns",
      "Evaluation methods",
      "Human-in-the-loop controls",
    ],
  }),
  defineEntity({
    id: "human-data",
    slug: "human-data",
    title: "Human Data",
    entityType: "technology",
    domain: "technology",
    summary:
      "Structures for history, signals, permissions and changing conditions without unrestricted collection. Represents authorized human context for careful interpretation and assistance.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["human-data-model", "privacy"],
    dependencyIds: [],
    usedByIds: ["human-data-model", "clinical-interfaces"],
    relatedTechnologyIds: ["privacy", "data-infrastructure", "security"],
    relatedSystemIds: [
      "human-data-model",
      "clinical-interfaces",
      "safety-layer",
    ],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["healthcare", "home", "hospitals"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Technology", href: "/technology/" }],
    futureTopics: [
      "Context schemas",
      "Minimization rules",
      "Consent and permission models",
    ],
  }),
  defineEntity({
    id: "robotics",
    slug: "robotics",
    title: "Robotics",
    entityType: "technology",
    domain: "technology",
    summary:
      "Engineering discipline for devices and interfaces that act in the physical world under governance. Enables physical interaction, mobility and assistance in real environments.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["robotics-layer", "drone-systems"],
    dependencyIds: [],
    usedByIds: ["robotics-layer", "drone-systems"],
    relatedTechnologyIds: ["automation", "interoperability"],
    relatedSystemIds: [
      "robotics-layer",
      "communication-layer",
      "safety-layer",
    ],
    relatedResearchIds: ["laboratories", "research-areas"],
    relatedApplicationIds: ["home", "hospitals", "industrial"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Technology", href: "/technology/" }],
    futureTopics: [
      "Manipulation boundaries",
      "Human-robot interaction",
      "Environment integration",
    ],
  }),
  defineEntity({
    id: "automation",
    slug: "automation",
    title: "Automation",
    entityType: "technology",
    domain: "technology",
    summary:
      "Controlled system behavior for tasks that can be delegated safely. Remains bounded by purpose, permission, risk and the ability for people to intervene.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["ai-decision-support", "drone-systems"],
    dependencyIds: [],
    usedByIds: ["ai-decision-support", "drone-systems", "safety-layer"],
    relatedTechnologyIds: ["artificial-intelligence", "robotics"],
    relatedSystemIds: [
      "ai-decision-support",
      "drone-systems",
      "safety-layer",
    ],
    relatedResearchIds: ["research-areas", "future-research"],
    relatedApplicationIds: ["emergency", "industrial", "agriculture"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Technology", href: "/technology/" }],
    futureTopics: [
      "Task delegation criteria",
      "Fallback behavior",
      "Review requirements",
    ],
  }),
  defineEntity({
    id: "privacy",
    slug: "privacy",
    title: "Privacy",
    entityType: "technology",
    domain: "technology",
    summary:
      "Architecture that limits what information may be used, why it may be used and who may access it. Reduces unnecessary exposure and keeps purpose limitation structural.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["trust-architecture", "human-data-model"],
    dependencyIds: [],
    usedByIds: ["human-data-model", "clinical-interfaces", "safety-layer"],
    relatedTechnologyIds: ["human-data", "security"],
    relatedSystemIds: [
      "human-data-model",
      "safety-layer",
      "communication-layer",
    ],
    relatedResearchIds: ["research-areas", "white-papers"],
    relatedApplicationIds: ["healthcare", "home", "hospitals"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Technology", href: "/technology/" },
      { label: "Trust", href: "/trust/" },
    ],
    futureTopics: [
      "Access control patterns",
      "Retention boundaries",
      "Purpose limitation checks",
    ],
  }),
  defineEntity({
    id: "security",
    slug: "security",
    title: "Security",
    entityType: "technology",
    domain: "technology",
    summary:
      "Protects systems, interfaces and authorized data pathways from misuse and unauthorized access. Supports trust architecture alongside privacy and safety; not a certification claim.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["trust-architecture", "safety-layer"],
    dependencyIds: [],
    usedByIds: ["communication-layer", "safety-layer", "knowledge-engine"],
    relatedTechnologyIds: ["privacy", "interoperability"],
    relatedSystemIds: [
      "communication-layer",
      "safety-layer",
      "knowledge-engine",
    ],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["hospitals", "government", "emergency"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Technology", href: "/technology/" },
      { label: "Trust", href: "/trust/" },
    ],
    futureTopics: [
      "Identity and access",
      "Interface hardening",
      "Audit pathways",
    ],
  }),
  defineEntity({
    id: "data-infrastructure",
    slug: "data-infrastructure",
    title: "Data Infrastructure",
    entityType: "technology",
    domain: "technology",
    summary:
      "Engineering substrate for storing, moving and governing authorized data. Serves the Human Data Model and system workflows under defined permissions.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["human-data-model", "knowledge-engine"],
    dependencyIds: [],
    usedByIds: [
      "human-data-model",
      "knowledge-engine",
      "communication-layer",
    ],
    relatedTechnologyIds: ["human-data", "interoperability", "security"],
    relatedSystemIds: [
      "human-data-model",
      "knowledge-engine",
      "communication-layer",
    ],
    relatedResearchIds: ["engineering-notes"],
    relatedApplicationIds: ["healthcare", "research", "government"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Technology", href: "/technology/" }],
    futureTopics: [
      "Data pathway maps",
      "Integrity controls",
      "Operational logging boundaries",
    ],
  }),
  defineEntity({
    id: "interoperability",
    slug: "interoperability",
    title: "Interoperability",
    entityType: "technology",
    domain: "technology",
    summary:
      "Defines how SAVEN Core systems exchange information with authorized external environments. Scoped, permissioned and subordinate to safety and privacy constraints.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["clinical-interfaces", "communication-layer"],
    dependencyIds: [],
    usedByIds: [
      "clinical-interfaces",
      "communication-layer",
      "knowledge-engine",
    ],
    relatedTechnologyIds: ["data-infrastructure", "security"],
    relatedSystemIds: [
      "clinical-interfaces",
      "communication-layer",
      "knowledge-engine",
    ],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["hospitals", "healthcare", "government"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Technology", href: "/technology/" }],
    futureTopics: [
      "Interface contracts",
      "Institutional integration patterns",
      "Compatibility boundaries",
    ],
  }),

  // —— Systems ——
  defineEntity({
    id: "human-data-model",
    slug: "human-data-model",
    title: "Human Data Model",
    entityType: "system",
    domain: "systems",
    summary:
      "Controlled interface between human context and systems that may use authorized information. Structured representation with permissions, minimization and accountable use.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["biomath-core", "trust-architecture"],
    dependencyIds: ["human-data", "data-infrastructure"],
    usedByIds: ["ai-decision-support", "clinical-interfaces"],
    relatedTechnologyIds: [
      "human-data",
      "privacy",
      "security",
      "interoperability",
      "data-infrastructure",
    ],
    relatedSystemIds: ["safety-layer", "ai-decision-support", "clinical-interfaces"],
    relatedResearchIds: ["research-areas", "engineering-notes"],
    relatedApplicationIds: [
      "healthcare",
      "home",
      "hospitals",
      "research",
    ],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      {
        label: "Human Data Model",
        href: "/technology/human-data-model/",
      },
      { label: "Technology", href: "/technology/" },
      { label: "Foundation", href: "/foundation/" },
    ],
    futureTopics: [
      "Context object definitions",
      "Permission matrices",
      "Change and review events",
    ],
  }),
  defineEntity({
    id: "ai-decision-support",
    slug: "ai-decision-support",
    title: "AI Decision Support",
    entityType: "system",
    domain: "systems",
    summary:
      "Assists interpretation and option evaluation without claiming autonomous decision authority. Pathways remain connected to rules, uncertainty handling and human oversight.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["clinical-interfaces", "safety-layer"],
    dependencyIds: ["human-data-model", "knowledge-engine"],
    usedByIds: ["clinical-interfaces"],
    relatedTechnologyIds: ["artificial-intelligence", "automation", "security"],
    relatedSystemIds: [
      "human-data-model",
      "knowledge-engine",
      "safety-layer",
      "clinical-interfaces",
    ],
    relatedResearchIds: ["research-areas", "white-papers"],
    relatedApplicationIds: ["healthcare", "emergency", "hospitals"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Systems", href: "/systems/" }],
    futureTopics: [
      "Option presentation patterns",
      "Escalation triggers",
      "Assistance boundaries",
    ],
  }),
  defineEntity({
    id: "robotics-layer",
    slug: "robotics-layer",
    title: "Robotics Layer",
    entityType: "system",
    domain: "systems",
    summary:
      "Connects intelligence and interfaces to physical assistance capabilities. Robotics systems for interaction, mobility and environment-level tasks under operational boundaries.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["drone-systems", "communication-layer"],
    dependencyIds: ["robotics", "automation"],
    usedByIds: [],
    relatedTechnologyIds: ["robotics", "automation", "interoperability"],
    relatedSystemIds: ["communication-layer", "safety-layer", "drone-systems"],
    relatedResearchIds: ["laboratories", "research-areas"],
    relatedApplicationIds: ["home", "hospitals", "industrial"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Systems", href: "/systems/" }],
    futureTopics: [
      "Device interface contracts",
      "Operational stop conditions",
      "Human-robot handoff",
    ],
  }),
  defineEntity({
    id: "drone-systems",
    slug: "drone-systems",
    title: "Drone Systems",
    entityType: "system",
    domain: "systems",
    summary:
      "Aerial operations framework for authorized sensing, inspection, mapping and monitoring. Constrained by permission, risk and human authority; not an operational deployment claim.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["robotics-layer", "communication-layer"],
    dependencyIds: ["robotics", "automation"],
    usedByIds: [],
    relatedTechnologyIds: ["robotics", "automation", "security"],
    relatedSystemIds: [
      "robotics-layer",
      "communication-layer",
      "safety-layer",
    ],
    relatedResearchIds: ["future-research", "laboratories"],
    relatedApplicationIds: [
      "agriculture",
      "emergency",
      "industrial",
      "government",
    ],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Systems", href: "/systems/" }],
    futureTopics: [
      "Mission authorization",
      "Sensing payloads",
      "Airspace and safety boundaries",
    ],
  }),
  defineEntity({
    id: "clinical-interfaces",
    slug: "clinical-interfaces",
    title: "Clinical Interfaces",
    entityType: "system",
    domain: "systems",
    summary:
      "Structured interfaces for clinical and care-environment workflows. Interface architecture for hospitals and care contexts; not a claim of medical-device approval or deployment.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["human-data-model", "ai-decision-support"],
    dependencyIds: ["human-data-model", "interoperability"],
    usedByIds: [],
    relatedTechnologyIds: ["human-data", "interoperability", "privacy"],
    relatedSystemIds: [
      "human-data-model",
      "ai-decision-support",
      "safety-layer",
      "communication-layer",
    ],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["healthcare", "hospitals", "emergency"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Systems", href: "/systems/" }],
    futureTopics: [
      "Workflow touchpoints",
      "Role-based access",
      "Institutional integration patterns",
    ],
  }),
  defineEntity({
    id: "knowledge-engine",
    slug: "knowledge-engine",
    title: "Knowledge Engine",
    entityType: "system",
    domain: "systems",
    summary:
      "Organizes engineering knowledge, models and governed references used across systems. Connects research, technology and system definitions without inventing publications.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["ai-decision-support", "research-areas"],
    dependencyIds: ["data-infrastructure", "artificial-intelligence"],
    usedByIds: ["ai-decision-support"],
    relatedTechnologyIds: [
      "artificial-intelligence",
      "data-infrastructure",
      "interoperability",
    ],
    relatedSystemIds: ["ai-decision-support", "safety-layer"],
    relatedResearchIds: [
      "research-areas",
      "engineering-notes",
      "publications",
    ],
    relatedApplicationIds: ["research", "healthcare", "government"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Systems", href: "/systems/" },
      { label: "Research", href: "/research/" },
    ],
    futureTopics: [
      "Knowledge indexes",
      "Model registries",
      "Evidence linkage patterns",
    ],
  }),
  defineEntity({
    id: "safety-layer",
    slug: "safety-layer",
    title: "Safety Layer",
    entityType: "system",
    domain: "systems",
    summary:
      "Encodes operational boundaries, escalation, fallback and conditions to stop or defer. Safety is a structural layer across systems, not a certification badge.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["trust-architecture"],
    dependencyIds: ["security", "privacy"],
    usedByIds: [
      "human-data-model",
      "ai-decision-support",
      "drone-systems",
      "robotics-layer",
    ],
    relatedTechnologyIds: ["security", "privacy", "automation"],
    relatedSystemIds: [
      "human-data-model",
      "ai-decision-support",
      "communication-layer",
    ],
    relatedResearchIds: ["research-areas", "future-research"],
    relatedApplicationIds: ["hospitals", "emergency", "home"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Systems", href: "/systems/" },
      { label: "Trust", href: "/trust/" },
    ],
    futureTopics: [
      "Boundary catalogs",
      "Failure handling patterns",
      "Human intervention points",
    ],
  }),
  defineEntity({
    id: "communication-layer",
    slug: "communication-layer",
    title: "Communication Layer",
    entityType: "system",
    domain: "systems",
    summary:
      "Defines how systems, people and authorized environments exchange signals and commands. Pathways remain permissioned, auditable where required and subordinate to safety constraints.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["drone-systems", "robotics-layer"],
    dependencyIds: ["interoperability", "security"],
    usedByIds: ["drone-systems", "clinical-interfaces"],
    relatedTechnologyIds: [
      "interoperability",
      "security",
      "data-infrastructure",
    ],
    relatedSystemIds: ["safety-layer", "drone-systems", "robotics-layer"],
    relatedResearchIds: ["engineering-notes"],
    relatedApplicationIds: ["hospitals", "industrial", "government"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Systems", href: "/systems/" }],
    futureTopics: [
      "Message contracts",
      "Latency and reliability classes",
      "Cross-system signaling",
    ],
  }),

  // —— Research ——
  defineEntity({
    id: "research-areas",
    slug: "research-areas",
    title: "Research Areas",
    entityType: "research-area",
    domain: "research",
    summary:
      "Groups the technical questions that shape architecture and system design, such as system models, safety, privacy and human-system interaction.",
    status: "research",
    parentId: null,
    childIds: [],
    relatedEntityIds: [
      "white-papers",
      "engineering-notes",
      "future-research",
    ],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: [
      "artificial-intelligence",
      "human-data",
      "privacy",
    ],
    relatedSystemIds: [
      "human-data-model",
      "safety-layer",
      "knowledge-engine",
    ],
    relatedResearchIds: [
      "white-papers",
      "engineering-notes",
      "future-research",
      "laboratories",
    ],
    relatedApplicationIds: ["research", "healthcare"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Research", href: "/research/" },
      { label: "Foundation", href: "/foundation/" },
      { label: "Technology", href: "/technology/" },
      { label: "Systems", href: "/systems/" },
    ],
    futureTopics: [
      "Area indexes",
      "Question registers",
      "Cross-links to systems",
    ],
  }),
  defineEntity({
    id: "white-papers",
    slug: "white-papers",
    title: "White Papers",
    entityType: "research-output",
    domain: "research",
    summary:
      "Structured place for approved long-form technical papers. Approved long-form technical papers and architecture notes.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["research-areas", "publications"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["artificial-intelligence", "privacy", "security"],
    relatedSystemIds: ["knowledge-engine", "safety-layer"],
    relatedResearchIds: ["research-areas", "publications"],
    relatedApplicationIds: [],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Research", href: "/research/" },
      { label: "Trust", href: "/trust/" },
    ],
    futureTopics: [
      "Paper metadata schema",
      "Public versus restricted classification",
      "Version history",
    ],
  }),
  defineEntity({
    id: "engineering-notes",
    slug: "engineering-notes",
    title: "Technical Notes",
    entityType: "research-output",
    domain: "research",
    summary:
      "Concise engineering observations that inform implementation. Short notes linking methods, constraints and open questions to systems and technology.",
    status: "active-development",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["research-areas", "knowledge-engine"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: [
      "data-infrastructure",
      "interoperability",
      "automation",
    ],
    relatedSystemIds: [
      "knowledge-engine",
      "human-data-model",
      "safety-layer",
    ],
    relatedResearchIds: ["research-areas", "future-research"],
    relatedApplicationIds: [],
    relatedTrustIds: [],
    relatedPageLinks: [
      { label: "Research", href: "/research/" },
      { label: "Systems", href: "/systems/" },
      { label: "Foundation", href: "/foundation/" },
    ],
    futureTopics: [
      "Note templates",
      "Status labels",
      "Traceability to systems",
    ],
  }),
  defineEntity({
    id: "publications",
    slug: "publications",
    title: "Publications",
    entityType: "research-output",
    domain: "research",
    summary:
      "Public research record for approved technical outputs. Entries are included when approved publications are available.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["white-papers", "company"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["artificial-intelligence"],
    relatedSystemIds: ["knowledge-engine"],
    relatedResearchIds: ["research-areas", "white-papers"],
    relatedApplicationIds: ["research"],
    relatedTrustIds: [],
    relatedPageLinks: [
      { label: "Research", href: "/research/" },
      { label: "Foundation", href: "/foundation/" },
    ],
    futureTopics: [
      "Citation fields",
      "Abstract summaries",
      "Related research areas",
    ],
  }),
  defineEntity({
    id: "future-research",
    slug: "future-research",
    title: "Future Research",
    entityType: "research-area",
    domain: "research",
    summary:
      "Tracks intended research directions without promising delivery dates. Forward-looking questions organized by capability and evidence needs.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["research-areas", "laboratories"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["automation", "privacy"],
    relatedSystemIds: ["safety-layer", "drone-systems", "human-data-model"],
    relatedResearchIds: ["research-areas", "laboratories"],
    relatedApplicationIds: ["research"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Research", href: "/research/" },
      { label: "Foundation", href: "/foundation/" },
      { label: "Trust", href: "/trust/" },
    ],
    futureTopics: [
      "Horizon topics",
      "Dependency on foundation layers",
      "Validation prerequisites",
    ],
  }),
  defineEntity({
    id: "laboratories",
    slug: "laboratories",
    title: "Laboratories",
    entityType: "research-area",
    domain: "research",
    summary:
      "Engineering environments that turn research into testable methods. Labs remain distinct from research; named labs appear only with approved terminology.",
    status: "research",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["research-areas", "robotics-layer"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["robotics", "automation", "security"],
    relatedSystemIds: [
      "robotics-layer",
      "safety-layer",
      "drone-systems",
    ],
    relatedResearchIds: ["research-areas", "future-research", "engineering-notes"],
    relatedApplicationIds: ["research", "industrial"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Research", href: "/research/" },
      { label: "Systems", href: "/systems/" },
      { label: "Technology", href: "/technology/" },
    ],
    futureTopics: [
      "Lab pages",
      "Focus areas",
      "Links to systems under test",
    ],
  }),

  // —— Applications ——
  defineEntity({
    id: "healthcare",
    slug: "healthcare",
    title: "Healthcare",
    entityType: "application",
    domain: "applications",
    summary:
      "Application architecture for care contexts with governed systems and human oversight. Not a claim of clinical deployment or device approval.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["hospitals", "home"],
    dependencyIds: [
      "clinical-interfaces",
      "human-data-model",
      "ai-decision-support",
    ],
    usedByIds: [],
    relatedTechnologyIds: ["human-data", "privacy", "artificial-intelligence"],
    relatedSystemIds: [
      "clinical-interfaces",
      "human-data-model",
      "ai-decision-support",
    ],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["hospitals", "home", "emergency"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Applications", href: "/applications/" },
      { label: "Trust", href: "/trust/" },
    ],
    futureTopics: [
      "Care workflow design",
      "Role boundaries",
      "Institutional collaboration notes",
    ],
  }),
  defineEntity({
    id: "home",
    slug: "home",
    title: "Home Application",
    entityType: "application",
    domain: "applications",
    summary:
      "Home-context architecture for independence, continuity and safer daily routines under permissions and privacy constraints.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["healthcare"],
    dependencyIds: ["human-data-model", "robotics-layer", "safety-layer"],
    usedByIds: [],
    relatedTechnologyIds: ["human-data", "robotics", "privacy"],
    relatedSystemIds: ["human-data-model", "robotics-layer", "safety-layer"],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["healthcare"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Applications", href: "/applications/" },
      { label: "Purpose", href: "/purpose/" },
    ],
    futureTopics: [
      "Daily routine assistance boundaries",
      "Household privacy rules",
      "Human intervention points",
    ],
  }),
  defineEntity({
    id: "hospitals",
    slug: "hospitals",
    title: "Hospitals",
    entityType: "application",
    domain: "applications",
    summary:
      "Hospital-context architecture for clinical environments, staff workflows and care infrastructure, aligned to foundation and trust requirements.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["healthcare", "emergency"],
    dependencyIds: [
      "clinical-interfaces",
      "safety-layer",
      "communication-layer",
    ],
    usedByIds: [],
    relatedTechnologyIds: ["interoperability", "privacy", "security"],
    relatedSystemIds: [
      "clinical-interfaces",
      "safety-layer",
      "communication-layer",
    ],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["healthcare", "emergency"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Applications", href: "/applications/" }],
    futureTopics: [
      "Staff workflow interfaces",
      "Environment integration",
      "Escalation pathways",
    ],
  }),
  defineEntity({
    id: "emergency",
    slug: "emergency",
    title: "Emergency",
    entityType: "application",
    domain: "applications",
    summary:
      "Time-critical assistance architecture under strict permissions and oversight. Architecture-level context; no operational deployment claims.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["hospitals", "healthcare"],
    dependencyIds: [
      "ai-decision-support",
      "drone-systems",
      "communication-layer",
    ],
    usedByIds: [],
    relatedTechnologyIds: ["automation", "artificial-intelligence", "security"],
    relatedSystemIds: [
      "ai-decision-support",
      "drone-systems",
      "communication-layer",
    ],
    relatedResearchIds: ["future-research"],
    relatedApplicationIds: ["hospitals", "government"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Applications", href: "/applications/" }],
    futureTopics: [
      "Rapid assessment support",
      "Remote assistance boundaries",
      "Authority and permission models",
    ],
  }),
  defineEntity({
    id: "industrial",
    slug: "industrial",
    title: "Industrial",
    entityType: "application",
    domain: "applications",
    summary:
      "Future industrial extensions that inherit the same foundation and trust constraints. Secondary to human applications; structure only, no product or customer claims.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["agriculture", "government"],
    dependencyIds: ["robotics-layer", "drone-systems", "safety-layer"],
    usedByIds: [],
    relatedTechnologyIds: ["robotics", "automation", "security"],
    relatedSystemIds: ["robotics-layer", "drone-systems", "safety-layer"],
    relatedResearchIds: ["laboratories"],
    relatedApplicationIds: ["agriculture", "government"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [{ label: "Applications", href: "/applications/" }],
    futureTopics: [
      "Inspection and monitoring patterns",
      "Operational safety boundaries",
      "Human application precedence rules",
    ],
  }),
  defineEntity({
    id: "government",
    slug: "government",
    title: "Government",
    entityType: "application",
    domain: "applications",
    summary:
      "Institutional and public-sector collaboration architecture. No partnership claims are made.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["industrial", "emergency"],
    dependencyIds: [
      "knowledge-engine",
      "communication-layer",
      "safety-layer",
    ],
    usedByIds: [],
    relatedTechnologyIds: ["security", "interoperability"],
    relatedSystemIds: [
      "knowledge-engine",
      "communication-layer",
      "safety-layer",
    ],
    relatedResearchIds: ["publications", "research-areas"],
    relatedApplicationIds: ["emergency", "industrial"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Applications", href: "/applications/" },
      { label: "Foundation", href: "/foundation/" },
    ],
    futureTopics: [
      "Institutional access models",
      "Accountability requirements",
      "Public-interest constraints",
    ],
  }),
  defineEntity({
    id: "agriculture",
    slug: "agriculture",
    title: "Agriculture",
    entityType: "application",
    domain: "applications",
    summary:
      "Agricultural applications of sensing and assistance systems. A secondary extension domain governed by the same architectural constraints.",
    status: "planned",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["industrial"],
    dependencyIds: [
      "drone-systems",
      "robotics-layer",
      "communication-layer",
    ],
    usedByIds: [],
    relatedTechnologyIds: ["robotics", "automation"],
    relatedSystemIds: [
      "drone-systems",
      "robotics-layer",
      "communication-layer",
    ],
    relatedResearchIds: ["future-research", "laboratories"],
    relatedApplicationIds: ["industrial"],
    relatedTrustIds: ["trust-architecture", "limitations"],
    relatedPageLinks: [{ label: "Applications", href: "/applications/" }],
    futureTopics: [
      "Field sensing patterns",
      "Aerial monitoring boundaries",
      "Environmental constraints",
    ],
  }),
  defineEntity({
    id: "research",
    slug: "research",
    title: "Research Applications",
    entityType: "application",
    domain: "applications",
    summary:
      "Application context for research settings that evaluate systems, methods and evidence. Distinct from the Research knowledge domain itself.",
    status: "conceptual",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["laboratories", "knowledge-engine"],
    dependencyIds: ["knowledge-engine", "human-data-model", "safety-layer"],
    usedByIds: [],
    relatedTechnologyIds: ["data-infrastructure", "artificial-intelligence"],
    relatedSystemIds: [
      "knowledge-engine",
      "human-data-model",
      "safety-layer",
    ],
    relatedResearchIds: ["research-areas", "laboratories", "future-research"],
    relatedApplicationIds: ["healthcare"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Applications", href: "/applications/" },
      { label: "Research", href: "/research/" },
      { label: "Foundation", href: "/foundation/" },
    ],
    futureTopics: [
      "Evaluation environments",
      "Controlled trial environments",
      "Links to laboratories",
    ],
  }),

  // —— Trust ——
  defineEntity({
    id: "trust-architecture",
    slug: "trust-architecture",
    title: "Trust Architecture",
    entityType: "trust",
    domain: "trust",
    summary:
      "Cross-cutting trust structure relating privacy, security, safety and human data. Not a child of one technical subsystem; constrains how systems and applications may operate.",
    status: "active-development",
    parentId: null,
    childIds: [
      "trust-privacy",
      "trust-security",
      "trust-safety",
      "human-oversight",
      "transparency",
      "ethics-responsible-use",
      "limitations",
    ],
    relatedEntityIds: [
      "human-data-model",
      "safety-layer",
      "privacy",
      "security",
    ],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["privacy", "security", "human-data"],
    relatedSystemIds: ["safety-layer", "human-data-model", "communication-layer"],
    relatedResearchIds: ["research-areas", "white-papers", "future-research"],
    relatedApplicationIds: [
      "healthcare",
      "home",
      "hospitals",
      "government",
    ],
    relatedTrustIds: [
      "trust-privacy",
      "trust-security",
      "trust-safety",
      "human-oversight",
      "transparency",
      "ethics-responsible-use",
      "limitations",
    ],
    relatedPageLinks: [
      { label: "Trust", href: "/trust/" },
      { label: "Purpose", href: "/purpose/" },
      { label: "Systems", href: "/systems/" },
    ],
    futureTopics: [
      "Permissions model pages",
      "Accountability registers",
      "Human oversight patterns",
    ],
  }),
  defineEntity({
    id: "trust-privacy",
    slug: "privacy",
    title: "Trust Privacy",
    entityType: "trust",
    domain: "trust",
    summary:
      "Organizational privacy commitments, purpose limits and accountable use. Distinct from Technology Privacy engineering foundations.",
    status: "active-development",
    parentId: "trust-architecture",
    childIds: [],
    relatedEntityIds: ["privacy", "trust-architecture", "human-oversight"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["privacy", "human-data", "security"],
    relatedSystemIds: ["human-data-model", "safety-layer"],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["healthcare", "home", "hospitals"],
    relatedTrustIds: ["trust-architecture", "transparency", "limitations"],
    relatedPageLinks: [
      { label: "Trust", href: "/trust/" },
      { label: "Technology Privacy", href: "/technology/privacy/" },
    ],
    futureTopics: [
      "Reviewed policy documents when approved",
      "Accountability records",
    ],
  }),
  defineEntity({
    id: "trust-security",
    slug: "security",
    title: "Trust Security",
    entityType: "trust",
    domain: "trust",
    summary:
      "Organizational security commitments and accountability expectations. Distinct from Technology Security engineering foundations.",
    status: "active-development",
    parentId: "trust-architecture",
    childIds: [],
    relatedEntityIds: ["security", "trust-architecture", "trust-safety"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["security", "privacy", "interoperability"],
    relatedSystemIds: ["communication-layer", "safety-layer"],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["hospitals", "government", "emergency"],
    relatedTrustIds: ["trust-architecture", "human-oversight", "limitations"],
    relatedPageLinks: [
      { label: "Trust", href: "/trust/" },
      { label: "Technology Security", href: "/technology/security/" },
    ],
    futureTopics: [
      "Incident response documentation",
      "Access accountability models",
    ],
  }),
  defineEntity({
    id: "trust-safety",
    slug: "safety",
    title: "Trust Safety",
    entityType: "trust",
    domain: "trust",
    summary:
      "Organizational safety commitments and limits. Distinct from the Systems Safety Layer, which documents system-wide control mechanisms.",
    status: "active-development",
    parentId: "trust-architecture",
    childIds: [],
    relatedEntityIds: ["safety-layer", "trust-architecture", "human-oversight"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["automation", "security"],
    relatedSystemIds: ["safety-layer", "ai-decision-support", "robotics-layer"],
    relatedResearchIds: ["research-areas", "future-research"],
    relatedApplicationIds: ["healthcare", "emergency", "industrial"],
    relatedTrustIds: ["trust-architecture", "limitations", "ethics-responsible-use"],
    relatedPageLinks: [
      { label: "Trust", href: "/trust/" },
      { label: "Safety Layer", href: "/systems/safety-layer/" },
    ],
    futureTopics: [
      "Escalation accountability records",
      "Safety review pathways",
    ],
  }),
  defineEntity({
    id: "human-oversight",
    slug: "human-oversight",
    title: "Human Oversight",
    entityType: "trust",
    domain: "trust",
    summary:
      "Requirement that people retain authority for significant decisions, review and escalation across SAVEN Core work.",
    status: "active-development",
    parentId: "trust-architecture",
    childIds: [],
    relatedEntityIds: ["trust-architecture", "ai-decision-support", "trust-safety"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["artificial-intelligence", "automation"],
    relatedSystemIds: ["ai-decision-support", "safety-layer", "knowledge-engine"],
    relatedResearchIds: ["research-areas"],
    relatedApplicationIds: ["healthcare", "home", "emergency"],
    relatedTrustIds: ["trust-architecture", "transparency", "ethics-responsible-use"],
    relatedPageLinks: [{ label: "Trust", href: "/trust/" }],
    futureTopics: [
      "Review role definitions",
      "Escalation ownership models",
    ],
  }),
  defineEntity({
    id: "transparency",
    slug: "transparency",
    title: "Transparency",
    entityType: "trust",
    domain: "trust",
    summary:
      "Expectation that sources, processing and limits can be explained to authorized people for review.",
    status: "active-development",
    parentId: "trust-architecture",
    childIds: [],
    relatedEntityIds: ["trust-architecture", "knowledge-engine", "human-oversight"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["artificial-intelligence", "data-infrastructure"],
    relatedSystemIds: ["knowledge-engine", "ai-decision-support"],
    relatedResearchIds: ["white-papers", "publications"],
    relatedApplicationIds: ["research", "healthcare"],
    relatedTrustIds: ["trust-architecture", "limitations", "human-oversight"],
    relatedPageLinks: [{ label: "Trust", href: "/trust/" }],
    futureTopics: [
      "Explanation patterns",
      "Source disclosure notes",
    ],
  }),
  defineEntity({
    id: "ethics-responsible-use",
    slug: "ethics-and-responsible-use",
    title: "Ethics and Responsible Use",
    entityType: "trust",
    domain: "trust",
    summary:
      "Commitments that guide when systems should refuse, escalate or remain under human control.",
    status: "active-development",
    parentId: "trust-architecture",
    childIds: [],
    relatedEntityIds: ["trust-architecture", "human-oversight", "limitations"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["artificial-intelligence", "automation"],
    relatedSystemIds: ["ai-decision-support", "safety-layer"],
    relatedResearchIds: ["research-areas", "future-research"],
    relatedApplicationIds: ["healthcare", "government", "research"],
    relatedTrustIds: ["trust-architecture", "trust-safety", "limitations"],
    relatedPageLinks: [{ label: "Trust", href: "/trust/" }],
    futureTopics: [
      "Refusal criteria documentation",
      "Responsible-use review notes",
    ],
  }),
  defineEntity({
    id: "limitations",
    slug: "limitations",
    title: "Limitations",
    entityType: "trust",
    domain: "trust",
    summary:
      "Explicit statement of what SAVEN Core does not claim, support or guarantee in current development.",
    status: "active-development",
    parentId: "trust-architecture",
    childIds: [],
    relatedEntityIds: ["trust-architecture", "ethics-responsible-use"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: ["privacy", "security"],
    relatedSystemIds: ["safety-layer"],
    relatedResearchIds: ["future-research"],
    relatedApplicationIds: ["healthcare", "emergency", "agriculture"],
    relatedTrustIds: [
      "trust-architecture",
      "trust-privacy",
      "trust-security",
      "trust-safety",
    ],
    relatedPageLinks: [{ label: "Trust", href: "/trust/" }],
    futureTopics: [
      "Expanded unsupported-scope catalog",
      "Escalation boundary examples",
    ],
  }),

  // —— Company ——
  defineEntity({
    id: "company",
    slug: "company",
    title: "Company",
    entityType: "company",
    domain: "company",
    summary:
      "Organizational frame for SAVEN Core as the company-level technology structure. Holds approved about, approach, collaboration and contact pathways without inventing facts.",
    status: "reference",
    parentId: null,
    childIds: [],
    relatedEntityIds: ["saven-core", "trust-architecture"],
    dependencyIds: [],
    usedByIds: [],
    relatedTechnologyIds: [],
    relatedSystemIds: ["knowledge-engine"],
    relatedResearchIds: ["publications", "laboratories"],
    relatedApplicationIds: ["government", "research"],
    relatedTrustIds: ["trust-architecture"],
    relatedPageLinks: [
      { label: "Foundation", href: "/foundation/" },
      { label: "Purpose", href: "/purpose/" },
      { label: "Research", href: "/research/" },
    ],
    futureTopics: [
      "About page structure",
      "Collaboration pathways",
      "Contact destinations",
    ],
  }),
];
