/**
 * Canonical list of published locale-relative routes.
 * Keep in sync with App Router page files under app/[locale].
 * Navigation and footer may only link destinations listed here
 * (auth sign-in is linked from chrome utilities; see assert exception).
 */

export const PUBLISHED_ROUTES = [
  "/",
  "/purpose/",
  "/foundation/",
  "/technology/",
  "/technology/human-data/",
  "/technology/human-data-model/",
  "/technology/data-infrastructure/",
  "/technology/interoperability/",
  "/technology/privacy/",
  "/technology/security/",
  "/technology/artificial-intelligence/",
  "/technology/automation/",
  "/technology/robotics/",
  "/systems/",
  "/systems/knowledge-engine/",
  "/systems/ai-decision-support/",
  "/systems/safety-layer/",
  "/systems/communication-layer/",
  "/systems/clinical-interfaces/",
  "/systems/robotics-layer/",
  "/systems/drone-systems/",
  "/applications/",
  "/applications/healthcare/",
  "/applications/home/",
  "/applications/hospitals/",
  "/applications/emergency/",
  "/applications/industrial/",
  "/applications/government/",
  "/applications/agriculture/",
  "/applications/research-applications/",
  "/trust/",
  "/trust/privacy/",
  "/trust/security/",
  "/trust/safety/",
  "/trust/human-oversight/",
  "/trust/transparency/",
  "/trust/ethics-and-responsible-use/",
  "/trust/limitations/",
  "/research/",
  "/research/areas/",
  "/research/notes/",
  "/roadmap/",
  "/labs/",
  "/labs/saven-robotics-lab/",
  "/labs/internal-future-lab/",
  "/systems/saven-robotics-interface/",
  "/investors/",
  "/investors/contact/",
  "/contact/",
  "/media/",
  "/resources/report-a-security-issue/",
  "/company/about/",
  "/auth/sign-in/",
  "/legal/",
  "/legal/privacy-policy/",
  "/legal/terms-of-use/",
  "/legal/cookie-policy/",
  "/legal/cookie-preferences/",
  "/legal/accessibility-statement/",
  "/legal/security/",
  "/legal/responsible-ai/",
  "/legal/medical-disclaimer/",
  "/legal/research-disclaimer/",
  "/legal/intellectual-property/",
  "/legal/trademark-notice/",
  "/legal/copyright/",
  "/legal/data-rights/",
  "/legal/regional-privacy-rights/",
  "/legal/do-not-sell-or-share/",
  "/legal/legal-notices/",
] as const;

export type PublishedRoute = (typeof PUBLISHED_ROUTES)[number];

export function isPublishedRoute(href: string): boolean {
  return (PUBLISHED_ROUTES as readonly string[]).includes(href);
}
